### ISSUE TITLE
Stale /tmp/vendoring-cache/ adds unexpected license files

### ISSUE THREAD

**Issue by jdufresne** [pradyunsg/vendoring#19]
vendoring==0.3.3

Steps to reproduce:

1. Use a clone of [pip](https://github.com/pypa/pip)
2. `git checkout 6b2ccdd10d8720cd8de5b7428277a2b0afe41bc1`
3. `vendoring sync . -v` results in no change (good)
4. `git checkout 653f12b5e794e4a6ca26fbb540d15850dd7c4e1e`
5. `vendoring sync . -v` results in `src/pip/_vendor/ipaddress.LICENSE` added (unexpected, this package was removed)

This looks to happen after removing a vendored package.

As a workaround, `rm -rf /tmp/vendoring-cache` followed by rerunning `vendoring` restores expected behavior.

**Comment by pradyunsg** [comment]
https://github.com/pradyunsg/vendoring/blob/718831add178c66db253e252eb89ebd971bef132/src/vendoring/tasks/license.py#L174

Happens because we're "just" looping through the downloaded packages, instead of checking if the package actually exists.

**Comment by pradyunsg** [comment]
Well, I ended up dropping the caching behaviour entirely in 655a654f3878ef38e9273f871fe251962843b36c. :)
