### ISSUE TITLE
import regex is a bit greedy with whitespace

### ISSUE THREAD

**Issue by jku** [pradyunsg/vendoring#29]
This might not come up that often in real projects but it does if you want to keep the test simple :)

This currently fails to vendor as the the first regex match eats the following newline which then means the second line does not match
```
import other
import other
```

I think the regexes should be simpler as multiline regexes anyway: I'll see if this makes sense to fix as part of #25

**Comment by pradyunsg** [comment]
Yea, we can probably change that to `(?=\s)` in that PR (at the cost of a bit of performance), and change the replacement regex too.
