### ISSUE TITLE
Can test on multiple Pythons again

### ISSUE THREAD

**Issue by henryiii** [pradyunsg/vendoring#30]
The official nox action (https://github.com/marketplace/actions/setup-nox) has been completely rewritten from a custom fork of setup-python into a completely trivial JS action, so it should be easy to tests on whatever Python versions are desired again.

This was dropped a while back, so thought I'd let you know that it's easy to do again, if you want to restore it.

**Comment by pradyunsg** [comment]
Thanks and duly noted!

I've personally decided to start treating this more like an application, that has limited compatibility. I'm fine with not testing this across various Python versions.
