### ISSUE TITLE
Typing stub should not be generated for libraries with typing support

### ISSUE THREAD

**Issue by uranusjr** [pradyunsg/vendoring#31]
Resolvelib 0.6.0 started carrying its own type stubs, but vendoring still generates a `resolvelib.pyi`. This seems to cause issues—not exactly sure about the cause.

I think vendoring can detect whether the vendored package contains a `py.typed` file and skip stub generation.

**Comment by pradyunsg** [comment]
For now, you can specify an empty list for the package in the stubs table, which should allow dealing with this situation.
