### ISSUE TITLE
Error out if the `requirements` is not in `protected-files` (if destination contains requirements)

### ISSUE THREAD

**Issue by jaraco** [pradyunsg/vendoring#38]
In https://github.com/pypa/setuptools/issues/2825, I started working on applying vendoring to setuptools. I stated with this definition:

```
[tool.vendoring]
destination = "setuptools/_vendor/"
requirements = "setuptools/_vendor/vendored.txt"
namespace = "setuptools._vendor"
```

I then ran `vendoring sync`, and it failed with:

```
setuptools main $ vendoring sync
Working in .
Load configuration... Done!
Clean existing libraries... Done!
Add vendored libraries...  
  Running pip install -t setuptools/_vendor -r setuptools/_vendor/vendored.txt --no-compile --no-deps
    ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'setuptools/_vendor/vendored.txt'
  Command exited with non-zero exit code: 1
```

It seems that it's necessary to specify:

```
protected-files = ["__init__.py", "README.rst", "vendored.txt"]
```

Perhaps vendoring could be smart enough to not delete the file indicated by `requirements` rather than requiring it to be specified twice.

**Comment by jaraco** [comment]
I'd also suggest that `__init__.py` should be protected by default, as it's unlikely (impossible?) that it will ever be part of a pip-installed package, but is likely needed by any `_vendor` package.

**Comment by pradyunsg** [comment]
I'll take a look tomorrow evening. :)

**Comment by jaraco** [comment]
I noticed you changed the bug title to only error rather than honor the original request to ignore these expected ignores by default. In my opinion, requiring each user of vendoring to supply the same "ignore" entries in their config is clumsy. In my opinion, I'd rather it "just work", rather than have it fail and then direct the user to investigate and/or copy/paste the fix from one repo to another.

That said, since #37 indicates that this project won't support the Setuptools requirements, it's not particularly important to me to address this issue.

**Comment by pradyunsg** [comment]
I'd still like to address this. :)

**Comment by pradyunsg** [comment]
369308a resolves this.
