### ISSUE TITLE
Can this be stepped back to a minimum python version requirement of 3.7?

### ISSUE THREAD

**Issue by whardier** [pradyunsg/vendoring#41]
Seems to work just fine - not sure if there is anything specific here leveraging anything in 3.8 (ordered dicts are probably useful)

**Comment by pradyunsg** [comment]
Thanks for filing this issue. I have very little interest in supporting older versions of Python. This tool is only intended for pip's own usecase, and pip's workflow can definitely accomodate for newer Python versions.

> This tool has no stability promises -- it has only one intended user: pip.

FWIW, I'm likely going to bump up to 3.9+ when I next spend some time on this, to clean up the type annotations. :)

**Comment by whardier** [comment]
Not a problem.  I simply have to create a vendor.txt built from a python3.7 environment to make sure all of the proper requirements are listed when 3.7 needs an alternative requirement.  I've supplemented our build scripts to only run vendorize via a virtual environment geared toward 3.8 (and soon 3.9 apparently!)

Vendoring gets a lot of judgement... yet many of those folks also use Node and other solutions that nest dependencies.  When developing CLI applications there is typically an 88.5% chance it would be bests off with vendored packages to avoid conflicting with project requirements.   I can go over the use case I keep tripping over job after job if there is ever a need to justify it.

I'd personally love to see more development in this project .. using ast or somehow roping in rope.  I'm tempted to give it a whirl but don't have the time.

This is a super useful tool - Thanks for reviewing the ticket.
