### ISSUE TITLE
`vendoring` vs `vendorize`

### ISSUE THREAD

**Issue by abitrolly** [pradyunsg/vendoring#46]
https://github.com/mwilliamson/python-vendorize exists from like 2015, so why not reuse that instead if creating a new tool from scratch?

`vendorize` looks stable, has documentation.

I am asking, because I need to choose the best tool.

**Comment by pradyunsg** [comment]
See https://github.com/pradyunsg/vendoring#why-does-this-exist

Don't use this.

**Comment by abitrolly** [comment]
I can not https://www.sobyte.net/post/2022-04/how-to-vendor-in-python/

**Comment by pradyunsg** [comment]
I don't control what other people write on their websites. :)

**Comment by abitrolly** [comment]
Therefore no choice, but to make it official. :D

I found that `vendorize` does not understand subdependencies. Making it less useful.
